### ISSUE TITLE
duplication in the data set

### ISSUE THREAD

**Issue by hj611** [WeixiangYAN/CodeTransOcean#2]
Hello！Thank you very much for your work. There is a lot of duplication in the data set, and multilingual_train.jsonl repeats almost every piece of data twice？

**Comment by WeixiangYAN** [comment]
Thank you for your support for our work. Each piece of data is repeated twice because in the experiments in Table 5, we found that when a piece of data (for example, from programming language A to programming language B) is expanded to from programming language B to programming language A to train the model, the performance of the model can be enhanced.

**Comment by hj611** [comment]
> 感谢大家对我们工作的支持，每条数据重复两次是因为在表5的实验中我们发现当把一条数据（比如从编程语言A到编程语言B）拓展到从编程语言B到编程语言A来训练模型时，模型的性能可以得到增强。

Thank you for your reply! Is there a documentation of the data, and for the code translation task, can the corresponding two languages in the same "id" translate each other? I found in the "train". In the json don't seem to realize one-to-one correspondence, such as CodeTransOcean/CodeTrans Datasets/MultilingualTrans /
multilingual_train.json: {"id": 126, "name": "Flow-control structures", "C++":  "#include <iostream> \n\nint main()\n{\n LOOP:\n  std::cout << \"Hello, World! \\n\"; \n goto LOOP; \n}\n", "C#": "int GetNumber() {\n    return 5; \n}\n"}

**Comment by WeixiangYAN** [comment]
{"id": 19241, "name": "Flow-control structures", "C#": "int GetNumber() {\n    return 5;\n}\n", "C++": "#include <iostream> \n\nint main()\n{\n LOOP:\n  std::cout << \"Hello, World!\\n\";\n goto LOOP;\n}\n"}

The above sample is the corresponding exchange of the target language and source language data. We don't have a file corresponding to each ID. But it is easy to separate, you only need to keep the first 1/2 of the file and delete the other half. Thank you!

**Comment by hj611** [comment]
> {"id": 19241, "name": "流控制结构", "C#": "int GetNumber() {\n return 5;\n}\n", "C++": "#include \n\nint main()\n{\n LOOP:\n std::cout << "Hello, World!\n";\n goto LOOP;\n}\n"}
> 
> 以上示例是目标语言和源语言数据的对应交换。我们没有每个ID对应的文件。但很容易分离，只需保留文件的前1/2并删除另一半即可。谢谢！

I'm sorry, maybe my question wasn't very clear. What I want to know is whether the code corresponding to the two languages in this data can translate each other? Because it looks like they're doing something completely different.

**Comment by WeixiangYAN** [comment]
Thank you very much for your careful observation! You are right, this is indeed a valuable finding. As stated in our paper, the dataset was collected from the Rosetta Code website (https://rosettacode.org/wiki/Rosetta_Code#). Although we invested significant effort in data collection and cleaning, given the diverse programming languages involved and the large volume of data, it was challenging to manually verify every single entry.
In the field of machine learning, it is a common phenomenon for training data to contain some degree of noise. However, your observation is particularly valuable and provides us with a direction for improvement. I will make note of this issue and work to further enhance data quality through methods such as sample verification in our future work.
Thank you again for your valuable feedback! This is very helpful in improving the quality of our dataset.
